name: Release aicommit

on:
  push:
    tags:
      - "v*" # Executa quando você fizer git push v1.0.0, v2.0.0 etc.

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Build binary
        run: |
          mkdir -p dist
          go build -o dist/aicommit ./cmd/aicommit  # ajuste se o entrypoint for diferente

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/aicommit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
