name: Auto Tag and Release

on:
  push:
    branches:
      - main

jobs:
  auto-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Get latest tag
        id: get_tag
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Bump version and create new tag
        id: bump_tag
        run: |
          OLD_TAG=${{ steps.get_tag.outputs.tag }}
          echo "Old tag: $OLD_TAG"

          VERSION=${OLD_TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          PATCH=$((PATCH + 1))
          NEW_TAG="v$MAJOR.$MINOR.$PATCH"

          echo "New tag: $NEW_TAG"
          git tag "$NEW_TAG"
          git push origin "$NEW_TAG"
